name: Build
on:
  push:
jobs:
  test:
    runs-on: ubuntu-18.04
    env:
      NODE_ENV: production
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: yarn install --production=false
      - run: yarn test:ci
